### ISSUE TITLE
Questões a serem resolvidas.

### ISSUE THREAD

**Issue by luanluciano93** [luanluciano93/infraestrura-otserv#1]
Quero a opinião de cada um, com argumento por favor, sobre os seguintes ASSUNTOS:

1 - VERSÃO DO TIBIA PARA O NOSSO PROJETO.
2 - IDEIAS PARA O LAYOUT DO WEBSITE.
3 - EXP DO SERVIDOR EM STAGES
4 - RECUPERAÇÃO DE MANA E LIFE DAS VOCAÇÕES.
5 - RUNAS E MUNIÇÕES (FLECHAS E ETC) INFINITAS.

Por enquanto é isso.

**Comment by luanluciano93** [comment]
1 - Voto seguir as atualizações do TFS que atualmente esta na versão 10,98. O styller base que vamos usar é baseado na versão 8.60, pois bem, precisamos adaptar várias coisas, features, mounts, outfits, quests para a versão 10.98 inicialmente, depois podemos pensar em avançar ... E outro argumento bem sólido é que assim a chance de termos bugs é bem menor quanto ao TFS.

2 - Voto no layout que criei antigamente para o new styller, coloquei uma print no grupo do whatsapp para quem quiser ver.

3 - Pensei em algo mediano em torno disso:
`	<stage minlevel="1" maxlevel="50" multiplier="200" />
	<stage minlevel="51" maxlevel="100" multiplier="100" />
	<stage minlevel="101" maxlevel="150" multiplier="70" />
	<stage minlevel="151" maxlevel="200" multiplier="50" />
	<stage minlevel="201" maxlevel="250" multiplier="25" />
	<stage minlevel="251" maxlevel="300" multiplier="15" />
	<stage minlevel="301" maxlevel="350" multiplier="8" />
	<stage minlevel="351" multiplier="5" />`

4 - RECUPERAÇÃO DE MANA E LIFE DAS VOCAÇÕES:
- Sorcerer: 40 life / 80 mana
- Druid: 40 life / 80 mana
- Paladin: 60 life / 60 mana
- Knight: 80 life / 40 mana

- MS: 50 life / 100 mana
- ED: 50 life / 100 mana
- RP: 80 life / 80 mana
- EK: 100 life / 50 mana

5 - Sempre joguei milhares de styller na versão 8.60, e sempre eram com runas infinitas, mas munições gastavam ...

**Comment by pedrogiampietro** [comment]
1 - 10x ~ 12x, cliente outdated acho que atraí mais pessoas por conta do bot, e um cliente 12 opcional, adicionar exp tipo 15% para quem usar, isso foca nos players que não usam bot.

2 - aceito sugestões também, mas ja to bolando algo.

3 - acho que depende do servidor que você almeja, eu gosto de umas stages hard tipo 

	**<stage minlevel="1" maxlevel="8" multiplier="28" />
	<stage minlevel="9" maxlevel="29" multiplier="16" />
	<stage minlevel="30" maxlevel="49" multiplier="14" />	
	<stage minlevel="50" maxlevel="74" multiplier="12" />
	<stage minlevel="75" maxlevel="94" multiplier="8" />	
	<stage minlevel="95" maxlevel="119" multiplier="6" />
	<stage minlevel="120" maxlevel="149" multiplier="4" />	
	<stage minlevel="150" maxlevel="199" multiplier="2" />
	<stage minlevel="200" multiplier="1" />**	

mas não sei se um styller assim, daria certo, pelo fato de ser um ot de teleports etcs.

5 - acho que não é maneiro runa e munições inifnitas, deveriam colocar para tudo acabar, o cara larga bot na cave sd infinita e assassin star, nunca mais vai refilar, só pra vender loot.
